Webアプリ開発2　8-1.入力した内容に該当するレコードのみを一覧表示する。
nosenami/tutorial pull request #29
Opened 2024-02-09 12:47 UTC by nosenami

検索機能を作成しました。
レビューのほどお願いいたします。

・検索機能を追加した。検索方法は、タイトル部分一致、または、ジャンル完全一致。
・（内部機能）本のジャンルのコード値とコード名称をマップに持たせて、コード値からコード名称を取得する関数と、コード名称からコード値を取得する関数を、作成した。

<img width="821" alt="20240209" src="https://github.com/nosenami/tutorial/assets/67619203/d5b5fedb-cda6-46f0-912e-45de55a9404b">

2024-02-12 05:42 UTC, h-yokoyama-eiwa requested changes
@nosenami 
コメントしました。

2024-02-12 05:42 UTC, h-yokoyama-eiwa commented on webAppliDevelop2/server/functions/select.js
> +export const selectBooksSearch = (searchText, searchType) => {
＜直しても直さなくても良いです。＞
selectBooksSearchという言葉に違和感があるなと感じました。
selectSearchedBooksとかの方がいいのではないかと。
そうするとselectBooksAllもselectAllBooksにした方が合うかなと。

2024-02-12 05:42 UTC, h-yokoyama-eiwa commented on webAppliDevelop2/server/functions/select.js
> +  if( searchType == 'searchType_title' ){
等価演算子は"==="（厳密等価演算子）を使うのが基本だと教わりました。
"=="だと値だけを比較、"==="だと値と型を比較するそうで。

2024-02-12 05:42 UTC, h-yokoyama-eiwa commented on webAppliDevelop2/server/functions/select.js
> +    let bookRecords = []
ここはconstでも良いのでは？

2024-02-12 09:06 UTC, ma-miyagawa requested changes
コメントしました。
横山さんの指摘の対応が終わり次第、LGTMとします。

2024-02-12 09:06 UTC, ma-miyagawa commented on webAppliDevelop2/server/functions/select.js
> +
オブジェクトや配列の値の変更は再代入にはならないため、constにしたほうが良いです。

https://qiita.com/cheez921/items/7b57835cb76e70dd0fc4

2024-02-13 06:48 UTC, esmtodoroki commented on webAppliDevelop2/server/functions/select.js
> +  // 検索条件がその他の場合は、WHERE条件なしとする。
単なる質問ですが、検索条件がその他になる場合の操作は、検索方法のラジオボタンをいずれも選択せずに、検索条件に語句を入れて検索するボタンを押下した場合になりますか？
また、その際の動きとしては、一覧のリフレッシュになるんですかね？

2024-02-13 06:50 UTC, esmtodoroki commented
指摘事項はありませんでしたが、1点質問だけさせてもらいました。

2024-02-13 08:54 UTC, k-shimada-esm commented
@nosenami 
1. 配列の持ち方と検索ですが、オブジェクト配列を使うとよいと思います。  
　コード値と名称を検索するロジックが、もしかしたら１～２行で書けちゃうかも。  
[Array.prototype.find() 関数](https://www.techiedelight.com/ja/find-value-array-objects-javascript/#:~:text=1.%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%20Array.prototype.find()%20%E9%96%A2%E6%95%B0)
2. SQL文字列を組み立てるときは、配列を使うとコードがさっぱりすると思います。  
[配列の結合](https://qiita.com/takeharu/items/d75f96f81ff83680013f#%E9%85%8D%E5%88%97%E3%81%AE%E7%B5%90%E5%90%88)

2024-02-18 09:38 UTC, nosenami commented on webAppliDevelop2/server/functions/select.js
> +export const selectBooksSearch = (searchText, searchType) => {
関数名を、selectBooksSearch から selectSearchedBooks に変更しました。
合わせて、selectBooksAll を selectAllBooks に変更しました。

自分でも一瞬違和感を感じたのですが、面倒がって元からあったselectBooksAll の名前に合わせてました。
指摘いただくレベルの違和感だと認識したので、名前を変更しました。

2024-02-18 09:38 UTC, nosenami commented on webAppliDevelop2/server/functions/select.js
> +  if( searchType == 'searchType_title' ){
比較演算子を === に変更しました。

2024-02-18 09:41 UTC, nosenami commented on webAppliDevelop2/server/functions/select.js
> +    let bookRecords = []
const に変更しました。

ループの中で値を変更（再代入）する使い方をしたくて、letだと思っていましたが、
配列の明細追加などは、値を変更（再代入）には当たらないことを知りました。

2024-02-18 09:41 UTC, nosenami commented on webAppliDevelop2/server/functions/select.js
> +
const に変更しました。

ループの中で値を変更（再代入）する使い方をしたくて、letだと思っていましたが、
配列の明細追加などは、値を変更（再代入）には当たらないことを知りました。

参考サイトありがとうございます。

2024-02-18 09:46 UTC, nosenami commented
@h-yokoyama-eiwa @ma-miyagawa 
指摘を対応いたしました。ご確認のほどお願いいたします。

まだ全ての指摘を対応できていませんが、日が空きそうなので、まずは一部コメント返信した部分のみ対応しました。

2024-02-20 10:58 UTC, h-yokoyama-eiwa requested changes
@nosenami 
「==」の箇所が残っていたようなので追加でコメントしました。

2024-02-20 10:58 UTC, h-yokoyama-eiwa commented on webAppliDevelop2/server/functions/functionsUtil.js
> +      if( value == kindName ){
ここも「==」ですね。

2024-02-24 08:50 UTC, nosenami commented on webAppliDevelop2/server/functions/select.js
> +  // 検索条件がその他の場合は、WHERE条件なしとする。
@esmtodoroki 
>検索条件がその他になる場合の操作は、検索方法のラジオボタンをいずれも選択せずに、検索条件に語句を入れて検索するボタンを押下した場合になりますか？

検索条件がその他になる場合とは、検索方法のラジオボタンをいずれも選択せずに、検索するボタンを押下した場合となります。
ただし実際には、画面で「タイトル部分一致」が初期状態で選択されているので、ありえないパターンとなります。

>また、その際の動きとしては、一覧のリフレッシュになるんですかね？

はい、where条件なしで検索しているので、画面初期表示と同じ動き（一覧のリフレッシュ）になります。

2024-03-03 09:06 UTC, nosenami commented
@k-shimada-esm 
> 1. 配列の持ち方と検索ですが、オブジェクト配列を使うとよいと思います。
>    　コード値と名称を検索するロジックが、もしかしたら１～２行で書けちゃうかも。

持ち方をオブジェクトの配列にして、検索はfind関数を使用するように変更しました。
オブジェクトで持った方が、keyとかvalueとかのプロパティの名前を付けられて、書きやすいと感じました。

内容のご確認のほどお願いいたします。

> 2. SQL文字列を組み立てるときは、配列を使うとコードがさっぱりすると思います。

すみませんが教えてください。
参考サイトを読んで配列を扱う関数が分かったのですが、配列を、文字列の組み立てにどのように使えばよいのかが、分かりませんでした。

2024-03-03 23:29 UTC, k-shimada-esm commented on webAppliDevelop2/server/functions/functionsUtil.js
> +]
コメントに「コード値とコード名称」とあるので、コメントと変数名は同じようにしたほうが良いと思いました。

2024-03-03 23:29 UTC, k-shimada-esm commented on webAppliDevelop2/server/functions/functionsUtil.js
> +  return foundArray.value
引数`kindKey` にジャンル定義にあるコードのみ入ってくることが約束されていればこのままでよいですが、そうでない時は`foundArray` が 'falsy' でないことを確認したほうが良いです。（多分、エラーになる）

2024-03-03 23:29 UTC, k-shimada-esm commented on webAppliDevelop2/server/functions/functionsUtil.js
> +  if( foundArray !== undefined){
`if( foundArray !== undefined){` と判断するより、`if( foundArray ){` と判断したほうがよいと思います。 `オブジェクトが返却された時` という判断になります。
[各型, 値の評価](https://qiita.com/phi/items/723aa59851b0716a87e3#%E5%90%84%E5%9E%8B-%E5%80%A4%E3%81%AE%E8%A9%95%E4%BE%A1)

2024-03-03 23:33 UTC, k-shimada-esm commented
@nosenami 
>> 1. 配列の持ち方と検索ですが、オブジェクト配列を使うとよいと思います。
>> 　コード値と名称を検索するロジックが、もしかしたら１～２行で書けちゃうかも。

> 持ち方をオブジェクトの配列にして、検索はfind関数を使用するように変更しました。
> オブジェクトで持った方が、keyとかvalueとかのプロパティの名前を付けられて、書きやすいと感じました。

リンク内容だけで理解してしまうなんて、さすがです。

>> 2. SQL文字列を組み立てるときは、配列を使うとコードがさっぱりすると思います。  

>すみませんが教えてください。
>参考サイトを読んで配列を扱う関数が分かったのですが、配列を、文字列の組み立てにどのように使えばよいのかが、分かりませんでした。

今のやり方に問題はないので、今のままでOKですよ。
実は私も課題レビューで山川さんからご指南いただきました。
push を使うとコードが読みやすく、メンテナンスもよいと思いました。
配列を使うというやり方を初めて知った時、感動したので。以下がその内容です。

>
> 例えば下記な感じですかね。正解はないですが。。
> 下記の関数を呼び出すだけ、みたいな。
> 
> ```
> function makeSqlWhere () {
>   if (!genre && !title) {
>     return ''
>   }
> 
>   const sqlWheres = []
> 
>   if (genre) {
>     sqlWheres.push(`genre collate utf8_unicode_ci = '${genre}'`)
>   }
> 
>   if (title) {
>     sqlWheres.push(`title collate utf8_unicode_ci LIKE '%${title}%'`)
>   }
> 
>   return `WHERE '${sqlWheres.join(' AND ')}'`
> }
> ```

2024-03-15 00:25 UTC, nosenami commented on webAppliDevelop2/server/functions/functionsUtil.js
> +]
@k-shimada-esm 
「コード値とコード名称」の変数名を、keyとvalue から、codeValueとcodeName に変更した。

2024-03-15 00:30 UTC, nosenami commented on webAppliDevelop2/server/functions/functionsUtil.js
> +  return foundArray.value
@k-shimada-esm 
findで見つかったかどうかを、トゥルーシーで聞いてから、returnするように修正しました。

2024-03-15 00:33 UTC, nosenami commented on webAppliDevelop2/server/functions/functionsUtil.js
> +  if( foundArray !== undefined){
@k-shimada-esm
findで見つかったかどうかを、トゥルーシーで聞くように修正しました。
undefined は false に該当するということが分かりました。

2024-03-15 00:55 UTC, nosenami commented on webAppliDevelop2/server/functions/functionsUtil.js
> +      if( value == kindName ){
@h-yokoyama-eiwa 
見逃していました。「===」に修正しました。（他の指摘修正によって書き方をif文じゃなくしました。）
「フォルダーを指定して検索」して、「==」が他にないことを確認しました。

2024-03-15 01:23 UTC, nosenami commented
@k-shimada-esm 
> push を使うとコードが読みやすく、メンテナンスもよいと思いました。
> 配列を使うというやり方を初めて知った時、感動したので。以下がその内容です。

配列のjoinというのを初めて知りました。
条件ひとつ分をpushしておけば、条件が複数個あったとしても、joinすれば「AND」でつなげて一文にできるのですね。
ありがとうございます。
今回は、課題では条件がひとつしかないので、今後機会があったらつかってみます。

2024-03-15 01:27 UTC, nosenami commented
@k-shimada-esm @h-yokoyama-eiwa 
指摘の対応を行いました。再度ご確認のほどお願いします。

2024-03-17 23:55 UTC, k-shimada-esm commented
LGTM 🙆  です。

2024-03-27 09:40 UTC, h-yokoyama-eiwa approved these changes

2024-03-27 09:40 UTC, h-yokoyama-eiwa commented
@nosenami 
すみません完全に忘れていました。
LGTMです。

2024-03-27 12:42 UTC, merged